# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170919_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='question_state',
            field=models.IntegerField(choices=[(0, 'new question'), (1, 'in progress'), (2, 'closed question')]),
        ),
    ]
